In [46]:
from sklearn import svm, datasets
iris = datasets.load_iris()

In [47]:
import pandas as pd
df = pd.DataFrame(iris.data, columns= iris.feature_names)

In [48]:
df['flower'] = iris.target

In [49]:
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x])

In [50]:
df.head()

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  flower
0                5.1               3.5  ...               0.2  setosa
1                4.9               3.0  ...               0.2  setosa
2                4.7               3.2  ...               0.2  setosa
3                4.6               3.1  ...               0.2  setosa
4                5.0               3.6  ...               0.2  setosa

[5 rows x 5 columns]

### train split

In [51]:
from sklearn.model_selection import train_test_split
X_train, X_test , y_train, y_test=train_test_split(iris.data,iris.target, test_size=0.2)

### SVM model

In [52]:
 iris_svm =  svm.SVC(kernel = 'rbf', C = 30, gamma ='auto')

In [53]:
iris_svm.fit(X_train,y_train)

SVC(C=30, gamma='auto')

In [54]:
iris_svm.score(X_test, y_test)

1.0

### K cross validation : k-Fold Cross-Validation splits data into k parts, trains the model k times on different subsets, and averages the results for a reliable performance estimate.

### cross_val_score evaluates a model's performance by running k-Fold Cross-Validation and returns the scores for each fold.

In [55]:
from sklearn.model_selection import cross_val_score

In [56]:
cross_val_score(svm.SVC(kernel= 'linear', C= 10, gamma = 'auto'),iris.data, iris.target, cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [57]:
cross_val_score(svm.SVC(kernel= 'rbf', C= 10, gamma = 'auto'),iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [58]:
cross_val_score(svm.SVC(kernel= 'rbf', C= 20, gamma = 'auto'),iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [59]:
import numpy as np
kernels = ['rbf','linear']
C = [1,10,20]
avg_scores = {}
for kval in kernels:
    for cval in C:
        cv_scores = cross_val_score(svm.SVC(kernel= kval, C= cval, gamma = 'auto'),iris.data, iris.target, cv=5)
        avg_scores[kval + '_' + str(cval)] = np.average(cv_scores)
avg_scores

{'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666}

### Grid Search CV : Grid Search CV exhaustively searches through all specified hyperparameter combinations, which can be very thorough but computationally expensive.

In [60]:
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(svm.SVC(gamma = 'auto'),{
    'C' : [1,10,20],
    'kernel' : ['rbf', 'linear']
    
}, cv=5, return_train_score=False)
clf.fit(iris.data,iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00046029, 0.00019941, 0.00021157, 0.00017819, 0.00020919,
        0.00017529]),
 'std_fit_time': array([2.39679322e-04, 1.04628548e-05, 1.30818604e-05, 1.42466622e-05,
        1.22405129e-05, 2.47496400e-06]),
 'mean_score_time': array([0.00021548, 0.0001184 , 0.00012503, 0.00010862, 0.00012197,
        0.00010796]),
 'std_score_time': array([6.93570096e-05, 7.00252860e-06, 5.56818412e-06, 2.87924369e-06,
        4.77456644e-06, 4.62163208e-06]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'ker

In [61]:
df = pd.DataFrame(clf.cv_results_)

In [62]:
df[['param_C',	'param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667

In [63]:
dir(clf)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_select_best_index',
 '_validate_data',
 '_validate_params',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'inverse_transform',
 'multimetric_',
 'n_fe

In [64]:
clf.best_score_

0.9800000000000001

In [65]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

### Randomized Search CV randomly samples from the hyperparameter space, offering a balance between search completeness and computational efficiency, and is often faster for large or complex hyperparameter spaces.

In [66]:
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(svm.SVC(gamma = 'auto'),{
    'C' : [1,10,20],
    'kernel' : ['rbf', 'linear']
}, cv=5, 
   return_train_score=False,
    n_iter=2 )
rs.fit(iris.data,iris.target)
pd.DataFrame(rs.cv_results_)[['param_C',	'param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1       linear             0.98
1       1          rbf             0.98