In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
df = pd.read_csv("homeprices.csv")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
model = linear_model.LinearRegression()
model.fit(df[["area"]], df.price)

LinearRegression()

In [4]:
model.predict(pd.DataFrame([[2000]],columns=["area"]))

array([452191.78082192])

## Pickle

In [5]:
import pickle

In [6]:
# save model
with open('model pickle','wb') as f:
    pickle.dump(model,f)

In [7]:
# load model from file into memory
with open('model pickle','rb') as f:
    ml= pickle.load(f)

In [8]:
ml.predict(pd.DataFrame([[2000]],columns=["area"]))

array([452191.78082192])

## Joblib

In [10]:
import joblib

In [12]:
#joblib api can take file name automatically
joblib.dump(model,'model_joblib')

['model_joblib']

In [13]:
mj= joblib.load('model_joblib')

In [14]:
mj.predict(pd.DataFrame([[2000]],columns=["area"]))

array([452191.78082192])