In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [35]:
df=pd.read_csv("homeprices_multi.csv")

In [36]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [37]:
# bedroom 2 col missing fill it with median
import math
median_bedroom = math.floor(df.bedrooms.median())
median_bedroom

4

In [38]:
df.bedrooms =df.bedrooms.fillna(median_bedroom)


In [39]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [40]:
lr = linear_model.LinearRegression()

In [41]:
lr.fit(df[["area","bedrooms","age"]],df.price)

LinearRegression()

In [49]:

pred= lr.predict(pd.DataFrame([[4200,4.0,20]],columns = ["area","bedrooms","age"]))
pred

array([720906.42016147])

In [51]:
pred1= lr.predict(pd.DataFrame([[2800,4.0,20]],columns = ["area","bedrooms","age"]))
pred1

array([564019.00144248])

In [52]:
pred1= lr.predict(pd.DataFrame([[2800,4.0,5]],columns = ["area","bedrooms","age"]))
pred1

array([612494.77007197])

## Excercise

In [3]:
df1 = pd.read_csv("hiring.csv")

In [4]:
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [6]:
!pip uninstall -y word2number



Found existing installation: word2number 1.1
Uninstalling word2number-1.1:
  Successfully uninstalled word2number-1.1
