In [200]:
import pandas as pd
import numpy as np

In [201]:
df = pd.read_csv("spam.csv")

In [202]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [203]:
df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [204]:
df['spam'] = df['Category'].apply(lambda x : 1 if x == 'spam' else 0)

In [205]:
df['spam']

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: spam, Length: 5572, dtype: int64

In [206]:
df

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [207]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [208]:
y_test

2257    0
1125    0
825     0
4566    0
742     0
       ..
206     0
800     0
232     0
294     0
3441    0
Name: spam, Length: 1115, dtype: int64

In [209]:
# count vectorizer
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_count = v.fit_transform(X_train.values)
X_train_count.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [210]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count, y_train)

MultinomialNB()

In [211]:
emails = [
    "Hi All, Meeting scheduled tommorrow morning , Please attend",
    "Congrats ! you are lucky won $1000 trip to london, Dont miss the chance"]
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [212]:
X_test_count = v.transform(X_test)
model.score(X_test_count,y_test)

0.9865470852017937

In [213]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb', MultinomialNB())
])

In [214]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [215]:
clf.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0])

In [216]:
clf.score(X_test,y_test)

0.9865470852017937

# Excercise

In [217]:
from sklearn.datasets import load_wine

In [218]:
wine = load_wine()

In [219]:
dir(wine)

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']

In [220]:
wine.data

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [221]:
wine.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [222]:
wine.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [223]:
wine.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [224]:
wine_df = (pd.DataFrame(wine.data, columns = wine.feature_names))
wine_df

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  
0                            3.92   1065.0  
1                            3.40   1050.0  
2                            3.17   1185.0  
3                            3.45   1480.0  
4                            2.93    735.0  
..                            ...      ...  
173                          1.74    740.0  
174                          1.56    750.0  
175                          1.56    835.0  
176                          1.62    840.0  
177                          1.60    560.0  

[178 rows x 13 columns]

In [225]:
wine_df['target'] = wine.target

In [226]:
wine_df

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  target  
0                            3.92   1065.0       0  
1                            3.40   1050.0       0  
2                            3.17   1185.0       0  
3                            3.45   1480.0       0  
4                            2.93    735.0       0  
..                            ...      ...     ...  
173                          1.74    740.0       2  
174                          1.56    750.0       2  
175                          1.56    835.0       2  
176                          1.62    840.0       2  
177                          1.60    560.0       2  

[178 rows x 14 columns]

In [227]:
wine_df.isna().sum()

alcohol                         0
malic_acid                      0
ash                             0
alcalinity_of_ash               0
magnesium                       0
total_phenols                   0
flavanoids                      0
nonflavanoid_phenols            0
proanthocyanins                 0
color_intensity                 0
hue                             0
od280/od315_of_diluted_wines    0
proline                         0
target                          0
dtype: int64

In [228]:
# Assume df is your pandas DataFrame with features and target
X = wine_df.drop('target', axis=1)  # Features
y = wine_df['target']  # Target variable

In [229]:
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [230]:
X_test

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
19     13.64        3.10  2.56               15.2      116.0           2.70   
45     14.21        4.04  2.44               18.9      111.0           2.85   
140    12.93        2.81  2.70               21.0       96.0           1.54   
30     13.73        1.50  2.70               22.5      101.0           3.00   
67     12.37        1.17  1.92               19.6       78.0           2.11   
16     14.30        1.92  2.72               20.0      120.0           2.80   
119    12.00        3.43  2.00               19.0       87.0           2.00   
174    13.40        3.91  2.48               23.0      102.0           1.80   
109    11.61        1.35  2.70               20.0       94.0           2.74   
141    13.36        2.56  2.35               20.0       89.0           1.40   
24     13.50        1.81  2.61               20.0       96.0           2.53   
150    13.50        3.12  2.62               24.0      123.0           1.40   
41     13.41        3.84  2.12               18.8       90.0           2.45   
118    12.77        3.43  1.98               16.0       80.0           1.63   
15     13.63        1.81  2.70               17.2      112.0           2.85   
111    12.52        2.43  2.17               21.0       88.0           2.55   
113    11.41        0.74  2.50               21.0       88.0           2.48   
82     12.08        1.13  2.51               24.0       78.0           2.00   
9      13.86        1.35  2.27               16.0       98.0           2.98   
114    12.08        1.39  2.50               22.5       84.0           2.56   
18     14.19        1.59  2.48               16.5      108.0           3.30   
66     13.11        1.01  1.70               15.0       78.0           2.98   
60     12.33        1.10  2.28               16.0      101.0           2.05   
169    13.40        4.60  2.86               25.0      112.0           1.98   
171    12.77        2.39  2.28               19.5       86.0           1.39   
164    13.78        2.76  2.30               22.0       90.0           1.35   
117    12.42        1.61  2.19               22.5      108.0           2.00   
65     12.37        1.21  2.56               18.1       98.0           2.42   
90     12.08        1.83  2.32               18.5       81.0           1.60   
55     13.56        1.73  2.46               20.5      116.0           2.96   
29     14.02        1.68  2.21               16.0       96.0           2.65   
128    12.37        1.63  2.30               24.5       88.0           2.22   
145    13.16        3.57  2.15               21.0      102.0           1.50   
31     13.58        1.66  2.36               19.1      106.0           2.86   
12     13.75        1.73  2.41               16.0       89.0           2.60   
42     13.88        1.89  2.59               15.0      101.0           3.25   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
19         3.03                  0.17             1.66         5.100000  0.96   
45         2.65                  0.30             1.25         5.240000  0.87   
140        0.50                  0.53             0.75         4.600000  0.77   
30         3.25                  0.29             2.38         5.700000  1.19   
67         2.00                  0.27             1.04         4.680000  1.12   
16         3.14                  0.33             1.97         6.200000  1.07   
119        1.64                  0.37             1.87         1.280000  0.93   
174        0.75                  0.43             1.41         7.300000  0.70   
109        2.92                  0.29             2.49         2.650000  0.96   
141        0.50                  0.37             0.64         5.600000  0.70   
24         2.61                  0.28             1.66         3.520000  1.12   
150        1.57                  0.22             1.25         8.600000  0.59   
41         2.68             

In [231]:
y_test

19     0
45     0
140    2
30     0
67     1
16     0
119    1
174    2
109    1
141    2
24     0
150    2
41     0
118    1
15     0
111    1
113    1
82     1
9      0
114    1
18     0
66     1
60     1
169    2
171    2
164    2
117    1
65     1
90     1
55     0
29     0
128    1
145    2
31     0
12     0
42     0
Name: target, dtype: int64

In [232]:
from sklearn.naive_bayes import GaussianNB

clf1 = Pipeline([
    ('nb', GaussianNB())
])


In [233]:
clf1.fit(X_train,y_train)

Pipeline(steps=[('nb', GaussianNB())])

In [234]:
clf1.predict(X_test)

array([0, 0, 2, 0, 1, 0, 1, 2, 1, 2, 0, 2, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 2, 2, 2, 1, 1, 1, 0, 0, 1, 2, 0, 0, 0])

In [235]:
clf1.score(X_test,y_test)

1.0

In [236]:
from sklearn.naive_bayes import GaussianNB

clf2 = Pipeline([
    ('nb', MultinomialNB())
])

In [238]:
clf2.fit(X_train,y_train)

Pipeline(steps=[('nb', MultinomialNB())])

In [239]:
clf2.predict(X_test)

array([0, 0, 2, 0, 1, 0, 1, 2, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       2, 2, 2, 2, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0])

In [240]:
clf2.score(X_test,y_test)

0.8888888888888888