## Numpy

1. NumPy is Python’s key library for scientific and numerical computing.
2. It centers around the **ndarray**, a powerful n-dimensional array object.
3. NumPy arrays are **fixed-size** and require elements of the same data type.
4. Faster than **Python lists—operations** are done in compiled code.
5. Supports **vectorization**: write **math operations** without loops.
6. **Broadcasting**: allows operations on **arrays with different shapes**.
7. Used widely in scientific Python packages, knowing NumPy is essential for advanced math and data tasks.
8. Flexible for both functional and object-oriented programming styles.

### Importing

In [595]:
import numpy as np

### Creating Arrays

* From list: np.array([1, 2, 3])
* Zeros: np.zeros(3) → [0. 0. 0.]
* Ones: np.ones(2) → [1. 1.]
* Range: np.arange(4) → [0 1 2 3]
* Linspace: np.linspace(0, 1, 5) → [0. 0.25 0.5 0.75 1.]

In [598]:
x = np.array([1,2,3,4,5,6])
x

array([1, 2, 3, 4, 5, 6])

In [599]:
x[2]

3

In [600]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [601]:
print('dimension of an array', a.ndim)

dimension of an array 2


In [602]:
print('length of an array', len(a))

length of an array 2


In [603]:
print('shape', a.shape)

shape (2, 2)


In [604]:
print('size', a.size)

size 4


In [605]:
a = np.array(
    [[[1,2,3],
     [3,4,5]]]
)
print(a)


[[[1 2 3]
  [3 4 5]]]


In [606]:
print('dimension of an array', a.ndim)

dimension of an array 3


In [607]:
print('shape', a.shape)

shape (1, 2, 3)


In [608]:
np.zeros(2)

array([0., 0.])

In [609]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [610]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

### NumPy Data Types and Type Conversion (astype)


**What are NumPy Data Types?**
* In NumPy, every array has a data type (called dtype), which describes the kind of elements it contains (like integer, float, complex, string, boolean, etc.).
* All elements in a NumPy array must have the **same dtype**. This is different from Python lists, which can hold mixed types.

**Why does dtype matter?**
* Determines the kind of operations you can do (e.g., you can’t add strings and numbers).
* Affects memory usage (an int8 uses less memory than a float64).
* Avoids accidental errors due to type mismatch.

**Viewing the Data Type of a NumPy Array**

In [615]:
import numpy as np

a = np.array([1, 2, 3])
print(a.dtype)  # Typically: int64 or int32

b = np.array([1.2, 3.4, 5.6])
print(b.dtype)  # float64


int64
float64


### NumPy Data Types Table

| Data Type                         | Code(s)                | Description       | Example                                      |
|----------------------------------|------------------------|-------------------|----------------------------------------------|
| `int8`, `int16`, `int32`, `int64` | `'i1'`, `'i2'`, `'i4'`, `'i8'` | Signed integer    | `np.array([1, 2], dtype='int16')`             |
| `uint8`, `uint16`, `uint32`, `uint64` | `'u1'`, `'u2'`, `'u4'`, `'u8'` | Unsigned integer  | `np.array([1, 2], dtype='uint8')`             |
| `float16`, `float32`, `float64`   | `'f2'`, `'f4'`, `'f8'` | Floating point    | `np.array([1., 2.], dtype='float32')`         |
| `complex64`, `complex128`         | `'c8'`, `'c16'`        | Complex numbers   | `np.array([1+2j], dtype='complex64')`         |
| `bool_`                           | `'?'`                 | Boolean           | `np.array([True, False])`                     |
| `S` (string), `U` (unicode)       | `'S'`, `'U'`          | String/Unicode    | `np.array(['abc'], dtype='S')`                |


In [617]:
m = np.array([23,34,5,1,3,45])
m

array([23, 34,  5,  1,  3, 45])

### Quick Reference Table

| Operation                         | Code Example                     | Notes                          |
|----------------------------------|----------------------------------|--------------------------------|
| Integer to float                 | `arr.astype(np.float64)`         | `1 → 1.0`                      |
| Float to integer                 | `arr.astype(np.int32)`           | `2.7 → 2`                      |
| Integer to string                | `arr.astype(str)`                | `5 → '5'`                      |
| String number to integer/float  | `arr.astype(int)` or `arr.astype(float)` | Must be valid string         |
| Any to boolean                   | `arr.astype(bool)`               | `0 → False`, else → `True`    |


In [619]:
print(np.sort(m))
    

[ 1  3  5 23 34 45]


In [620]:
np.argsort(m) # sort as per indices

array([3, 4, 2, 0, 1, 5])

In [621]:
d = np.array([12,3,10,20])
f = np.array([20,30,40,50])

z = np.concatenate((d,f))
print(z)

[12  3 10 20 20 30 40 50]


In [622]:
arr = np.arange(2,14,2)
print(arr)

[ 2  4  6  8 10 12]


In [623]:
g = arr.reshape(2,3)
g

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [624]:
g = arr.reshape(3,2)
g

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [625]:
# Index

In [626]:
f = np.array([0,1,2,45,55,89,3,33,45])
print(f)

[ 0  1  2 45 55 89  3 33 45]


In [627]:
f[:2]

array([0, 1])

In [628]:
f[3:5]

array([45, 55])

In [629]:
f[:4]

array([ 0,  1,  2, 45])

In [630]:
m = np.array([0,1,2,45,55,89,3,33,45])
print(m)

[ 0  1  2 45 55 89  3 33 45]


In [631]:
m[-3:-1]

array([ 3, 33])

In [632]:
m[-4:-1]

array([89,  3, 33])

In [633]:
m[-1:-3] # after 45 no element is present to print

array([], dtype=int64)

In [634]:
m[-1:-3: -1] # if we add step function -1 then it changes the direction to backward and prints the elements

array([45, 33])

In [635]:
m<30

array([ True,  True,  True, False, False, False,  True, False, False])

In [636]:
m[m<40]

array([ 0,  1,  2,  3, 33])

In [637]:
n = np.array([[10,3,42],[2,30,4],[22,45,2]])
n

array([[10,  3, 42],
       [ 2, 30,  4],
       [22, 45,  2]])

In [638]:
n.shape

(3, 3)

In [639]:
n[1:5]

array([[ 2, 30,  4],
       [22, 45,  2]])

In [640]:
n[(n<7) | (n<30)]

array([10,  3,  2,  4, 22,  2])

### Array Properties and Utility Functions 

In [642]:
a = np.arange(12).reshape(3,4)
print(a.shape)     # (3,4)
print(a.ndim)      # 2
print(a.size)      # 12
print(a.itemsize)  # Bytes per element
print(a.nbytes)    # Total bytes
print(a.T)         # Transpose
np.fill_diagonal(a, -1)
print(a)


(3, 4)
2
12
8
96
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[-1  1  2  3]
 [ 4 -1  6  7]
 [ 8  9 -1 11]]


### Arithmetic and Aggregate Functions 


In [644]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)         # [5 7 9], elementwise addition
print(a.mean())      # 2.0
print(a.sum())       # 6
print(b.max())       # 6
print(a.cumsum())    # [1, 3, 6]


[5 7 9]
2.0
6
6
[1 3 6]


### Linear Algebra Routines

In [646]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.dot(a, b))            # Matrix multiplication
print(np.linalg.inv(a))        # Inverse of matrix
print(np.linalg.eig(a))        # Eigenvalues/vectors
print(np.linalg.det(a))        # Determinant


[[19 22]
 [43 50]]
[[-2.   1. ]
 [ 1.5 -0.5]]
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
-2.0000000000000004


### np.hstack() and np.vstack()



In [648]:
a1 = np.array([[1,2,3,4],[10,20,30,40]])
a2 = np.array([[5,10,15,20],[25,35,45,50]])

**np.vstack()** Stacks (joins) arrays in sequence vertically (row-wise).
**The arrays are joined one after the other (rows increase).**

In [650]:
np.vstack((a1,a2))

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40],
       [ 5, 10, 15, 20],
       [25, 35, 45, 50]])

**np.hstack()** - Stacks (joins) arrays in sequence horizontally (column-wise).
**The arrays are joined side by side (columns increase).**

In [652]:
np.hstack((a1,a2))

array([[ 1,  2,  3,  4,  5, 10, 15, 20],
       [10, 20, 30, 40, 25, 35, 45, 50]])

### View vs Copy in NumPy

**View** : A view is a **new array object that looks at the same data as the original array (no actual data is copied).**
**Changing data in the view changes the original array, and vice versa.**

In [655]:
import numpy as np

# Original array
a = np.array([1, 2, 3, 4, 10,15])
# Create a view
b = a[:4]  # Slice creates a view
print("Original a:", a)
print("View b:", b)




Original a: [ 1  2  3  4 10 15]
View b: [1 2 3 4]


In [656]:
# Modify the view
b[0] = 9
print("Modified b:", b)
print("Original a after modifying b:", a)


Modified b: [9 2 3 4]
Original a after modifying b: [ 9  2  3  4 10 15]


**Copy** A copy is a **new array object** with its own separate data, independent of the original array.
**Changing data in the copy does NOT affect the original array.**

In [658]:
# Original array
a = np.array([1, 2, 3, 4])
# Create a copy
c = a.copy()  # Explicit copy
print("Original a:", a)
print("Copy c:", c)



Original a: [1 2 3 4]
Copy c: [1 2 3 4]


In [659]:
# Modify the copy
c[0] = 99
print("Modified c:", c)
print("Original a after modifying c:", a)

Modified c: [99  2  3  4]
Original a after modifying c: [1 2 3 4]


In [660]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = a[:2]  # View via slicing
b[0] = 99
print("View b:", b)        # [99  2]
print("Original a:", a)    # [99  2  3  4]
print(b.base is a)         # True (shares data)

View b: [99  2]
Original a: [99  2  3  4]
True


In [661]:
a = np.array([1, 2, 3, 4])
c = a.copy()  # Explicit copy
c[0] = 99
print("Copy c:", c)        # [99  2  3  4]
print("Original a:", a)    # [1 2 3 4] (unchanged)
print(c.base is None)      # True (independent data)

Copy c: [99  2  3  4]
Original a: [1 2 3 4]
True


### **flatten() vs ravel() in NumPy**

**flatten()**
* Returns a new 1D copy of the array (always copies data).
* Changes made to the flattened array do not affect the original array.

In [664]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = a.flatten()
b[0] = 99
print(a)  # [[1 2]
          #  [3 4]]
print(b)  # [99 2 3 4]


[[1 2]
 [3 4]]
[99  2  3  4]


**ravel()** 
* Returns a flattened 1D array; it is a view if possible (no copy), otherwise a copy (if needed).
* Changes to ravel’s result may affect the original array (if it is a view).

In [666]:
a = np.array([[1, 2], [3, 4]])
b = a.ravel()
b[0] = 99
print(a)  # [[99  2]
          #  [ 3  4]]
print(b)  # [99 2 3 4]


[[99  2]
 [ 3  4]]
[99  2  3  4]


### Accessing Documentation & Help

In [668]:
help(np.mean)
# In IPython or Jupyter
# np.mean?


Help on _ArrayFunctionDispatcher in module numpy:

mean(a, axis=None, dtype=None, out=None, keepdims=<no value>, *, where=<no value>)
    Compute the arithmetic mean along the specified axis.

    Returns the average of the array elements.  The average is taken over
    the flattened array by default, otherwise over the specified axis.
    `float64` intermediate and return values are used for integer inputs.

    Parameters
    ----------
    a : array_like
        Array containing numbers whose mean is desired. If `a` is not an
        array, a conversion is attempted.
    axis : None or int or tuple of ints, optional
        Axis or axes along which the means are computed. The default is to
        compute the mean of the flattened array.

        .. versionadded:: 1.7.0

        If this is a tuple of ints, a mean is performed over multiple axes,
        instead of a single axis or all the axes as before.
    dtype : data-type, optional
        Type to use in computing the mean.  For